{
    "apps": [
        {
            "arch": "mipsle", 
            "build_date": "2024-10-28_08:20:13", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "f3a88d69b298251c8c16438bcf58362d", 
            "name": "frps", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "2.1"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-30_11:14:29", 
            "description": "简便高效的异地组网、内网穿透工具", 
            "home_url": "Module_vnt.asp", 
            "md5": "7f5e9c2560e2595ee7d402b34b2011ea", 
            "name": "vnt", 
            "tar_url": "vnt/vnt.tar.gz", 
            "title": "vnt", 
            "version": "1.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-29_11:03:05", 
            "description": "node.js", 
            "home_url": "Module_node.asp", 
            "md5": "241619d7006b5b7c5e60439c1e2ea417", 
            "name": "node", 
            "tar_url": "node/node.tar.gz", 
            "title": "node.js", 
            "version": "0.0.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-30_10:36:47", 
            "description": "tailscale", 
            "home_url": "Module_tailscale.asp", 
            "md5": "9f48d638c7b05eda21181397fa9fe248", 
            "name": "tailscale", 
            "tar_url": "tailscale/tailscale.tar.gz", 
            "title": "tailscale", 
            "version": "0.0.8"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-30_07:40:03", 
            "description": "Socat 端口转发", 
            "home_url": "Module_socat.asp", 
            "md5": "906d03ac1225107d0683d57222809ffa", 
            "name": "socat", 
            "tar_url": "socat/socat.tar.gz", 
            "title": "Socat端口转发", 
            "version": "1.1"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-30_09:17:13", 
            "description": "局域网网速测试工具", 
            "home_url": "Module_speedtest.asp", 
            "md5": "29f8011615c768b41f07153295b6279c", 
            "name": "speedtest", 
            "tar_url": "speedtest/speedtest.tar.gz", 
            "title": "局域网测速", 
            "version": "0.0.4"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-25_23:03:11", 
            "description": "FileBrowser：您的可视化路由文件管理系统", 
            "home_url": "Module_filebrowser.asp", 
            "md5": "62d38887a689f7d2dc9d4d17e886fa86", 
            "name": "filebrowser", 
            "tar_url": "filebrowser/filebrowser.tar.gz", 
            "title": "filebrowser", 
            "version": "1.0.7"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-28_22:29:07", 
            "description": "去广告，没烦恼", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "eb4437ac98bed748dc78a00b64a869eb", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "koolproxy", 
            "version": "3.8.5.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-24_10:31:40", 
            "description": "阿里云盘 WebDAV 服务器", 
            "home_url": "Module_aliyundrivewebdav.asp", 
            "md5": "e5f94bfa7ece355dbc0126b8251b2858", 
            "name": "aliyundrivewebdav", 
            "tar_url": "aliyundrivewebdav/aliyundrivewebdav.tar.gz", 
            "title": "阿里云盘WebDAV", 
            "version": "1.8.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-30_09:19:25", 
            "description": "老板，来一斤虚拟内存~", 
            "home_url": "Module_swap.asp", 
            "md5": "6201e77364b336822670eb46e00d1229", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-29_11:39:06", 
            "description": "花生壳内网穿透", 
            "home_url": "Module_phddns.asp", 
            "md5": "689a2ad50c489e4e4644de4f50841c66", 
            "name": "phddns", 
            "tar_url": "phddns/phddns.tar.gz", 
            "title": "花生壳内网穿透", 
            "version": "3.0.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-30_11:16:49", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "1573c07bf4b12216cbbf49fa1b9d5d23", 
            "name": "zerotier", 
            "tar_url": "zerotier/zerotier.tar.gz", 
            "title": "zerotier", 
            "version": "1.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-30_11:07:04", 
            "description": "解锁网易云灰色歌曲", 
            "home_url": "Module_unblockmusic.asp", 
            "md5": "b1dfd1248cc1e00301f730678f04c554", 
            "name": "unblockmusic", 
            "tar_url": "unblockmusic/unblockmusic.tar.gz", 
            "title": "解锁网易云灰色歌曲", 
            "version": "1.2.1"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-24_12:55:50", 
            "description": "Cloudflare解析自动更新IP", 
            "home_url": "Module_cfddns.asp", 
            "md5": "791c074d158abce759e8d286a29d0043", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "Cloudflare DDNS", 
            "version": "1.9"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-29_08:58:27", 
            "description": "灵缇游戏加速插件", 
            "home_url": "Module_lingti.asp", 
            "md5": "c24bd1ec6dc1e0d9525825e3ab7ff3fb", 
            "name": "lingti", 
            "tar_url": "lingti/lingti.tar.gz", 
            "title": "灵缇游戏加速插件", 
            "version": "1.0.3"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-28_08:53:58", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "4c0c0753737c7a9ed130425ae6d00e32", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "2.0"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-29_15:09:02", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "854fc8aa5bc9f63ee3e0788e5ed0d117", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.5"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-25_08:51:26", 
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback", 
            "home_url": "Module_ddns.asp", 
            "md5": "3c11ede6068933808f5b267838598693", 
            "name": "ddns", 
            "tar_url": "ddns/ddns.tar.gz", 
            "title": "多ddns合一", 
            "version": "0.3"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-30_11:10:45", 
            "description": "自己的私有云", 
            "home_url": "Module_verysync.asp", 
            "md5": "10c8741e7a2b512d5113e42035621089", 
            "name": "verysync", 
            "tar_url": "verysync/verysync.tar.gz", 
            "title": "微力同步", 
            "version": "1.1.1"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-24_07:35:41", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "0efd9abbb21da696536155c1b823fcbc", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.5"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-26_16:21:21", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frpc.asp", 
            "md5": "dfcf777d0984534b76bed76735437c49", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc穿透", 
            "version": "2.5"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-24_07:48:18", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "1167574d69688d6bed6a531809420946", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-24_07:44:31", 
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站", 
            "home_url": "Module_adbyby.asp", 
            "md5": "630db5c32b03635a3557a5f5a35228a4", 
            "name": "adbyby", 
            "tar_url": "adbyby/adbyby.tar.gz", 
            "title": "广告屏蔽大师 Plus", 
            "version": "1.4"
        }, 
        {
            "build_date": "2020-08-20_11:41:43", 
            "description": "迅雷快鸟，为上网加速而生~", 
            "home_url": "Module_fastd1ck.asp", 
            "md5": "4db9a9b350e0d5037a38c3d05f8e3d88", 
            "name": "fastd1ck", 
            "tar_url": "fastd1ck/fastd1ck.tar.gz", 
            "title": "讯雷快鸟", 
            "version": "1.8"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-29_11:07:41", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "5c2b09ed1f8ef2efe7d12f5aba9bd9cb", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.7"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-24_11:00:07", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "59cd495d1d1a64bf08880bd82476fe66", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "3.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-24_19:14:02", 
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)", 
            "home_url": "Module_cloudflared.asp", 
            "md5": "edca3bf943a79d59fadc7ac0d8b33c71", 
            "name": "cloudflared", 
            "tar_url": "cloudflared/cloudflared.tar.gz", 
            "title": "cloudflared", 
            "version": "1.1"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-29_11:45:01", 
            "description": "这是一只自动帮你签到的dog", 
            "home_url": "Module_qiandao.asp", 
            "md5": "c1aeb63a7c44d41e49642d9763469997", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "签到dog", 
            "version": "1.8"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-29_10:39:16", 
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台", 
            "home_url": "Module_lookcat.asp", 
            "md5": "5bf85ac90ef99da2acd49c3b9569b816", 
            "name": "lookcat", 
            "tar_url": "lookcat/lookcat.tar.gz", 
            "title": "光猫助手", 
            "version": "1.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-29_23:01:10", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "255e3761b5ac4e5bd8a0f2962664737b", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "ServerChan微信推送", 
            "version": "2.7"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-25_09:05:09", 
            "description": "使用Dnspod的ddns服务", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "079b517d6e8c520d15e58c0670196309", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "DDnspod", 
            "version": "2.0"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-24_10:23:04", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。", 
            "home_url": "Module_alist.asp", 
            "md5": "71a0230323f5eaa10a152ef9fa6a9715", 
            "name": "alist", 
            "tar_url": "alist/alist.tar.gz", 
            "title": "Alist文件列表", 
            "version": "1.9.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-24_11:39:17", 
            "description": "百度盘", 
            "home_url": "Module_baidupcs.asp", 
            "md5": "3242ae2afc345eeea26be9555f10651f", 
            "name": "baidupcs", 
            "tar_url": "baidupcs/baidupcs.tar.gz", 
            "title": "百度盘", 
            "version": "1.9"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-25_23:08:49", 
            "description": "DDNSTO远程控制", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "f36aaae3ab5207635be40c019afb01d0", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "DDNSTO远程控制", 
            "version": "3.0.3"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-30_11:02:06", 
            "description": "腾讯云ddns", 
            "home_url": "Module_tenddns.asp", 
            "md5": "f1fe629da0bb9c8c951dc9c906a2fc03", 
            "name": "tenddns", 
            "tar_url": "tenddns/tenddns.tar.gz", 
            "title": "腾讯云ddns", 
            "version": "0.0.4"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/paldier/softcentermipsle/master", 
    "md5": "8c21cc1ce2a01ce3f20138aab4546383", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.5.3"
}